from app.schemas.climate_submission_schema import *
from app.schemas.mobility_submission_schema import *
from app.schemas.mobility_result_schema import *
from app.schemas.mobility_subresult_schema import *
from app.schemas.municipality_schema import *
from app.schemas.main_objective_schema import *
from app.schemas.sub_objective_schema import *
from app.schemas.tag_schema import *
from app.schemas.indicator_schema import *
from app.schemas.text_block_schema import *
from app.schemas.user_schema import *
